### PR TITLE
Include primitive JNI signatures

### LINKED ISSUE #65: Invalid JNI signature resulted from method calls
**Describe the bug**
* Inner method calls cause an `Invalid JNI Signature "` error in `HelloMethod`. 
* Inserted a breakpoint at `hello(int i):23`, but that is never reached because of the `Invalid JNI` issue
08-18-22 invalid jni

 **To Reproduce**
Use NativeJDB on `HelloMethod` and insert breakpoint at lines 11 and 23. Hit Continue to second breakpoint, and you will see JNI signature invalid occurring.

### PR DESCRIPTION
**Pull request by jchen10500**
Fixes #65 

- Fixes `Invalid JNI signature "` for `hello(int i)` method call in `HelloMethod`  by filling in translation for primitive parameters (read more below) 
- Primitive arguments and `$asm` variable show up as expected 
- Possible enhancement: may need more testing for translating GDB to JNI signatures 

08-18-22 valid jni signature

**Cause of bug**
* Invalid JNI results from `JDWPMethods-VariablesWithGeneric` retrieving GDB locals and comparing those with the locals obtained from the VM ([here](https://github.com/nativejdb/nativejdb/blob/value/src/main/java/jdwp/JDWPMethod.java#L206))
* Mismatch between GDB and IDE/VM locals led to NativeJDB providing an empty signature on this [line](https://github.com/nativejdb/nativejdb/blob/value/src/main/java/jdwp/JDWPMethod.java#L244)
08-18-22 gdb and vm var mismatch

* Main reason that caused mismatch between VM and GDB variables was that thread frame should be in `hello(int i)` and not `main`
* The list of commands issued for `ThreadReference (11)` is: 
1. FrameCount (7)
2. Name (1)
3. Status (4)
4. Frames (6)
* In FrameCount and Frames, the location of all frames is required. Location includes the JNI signature for the method the frame represents 
* `Translator.locationLookUp` is used to [translate](https://github.com/nativejdb/nativejdb/blob/value/src/main/java/jdwp/Translator.java#L206) GDB's method signature to the one JDWP understands. However, it is missing the translation for primitive parameters like `"int"` to `"I"` 
* Example: GDB provides `HelloMethod.HelloMethod::hello(int)` but JDWP expects `HelloMethod/HelloMethod::hello(I)`

08-18-22 gdb to jni translation

* This PR fixes the problem that primitive parameters like `int` are not translated

### CODE REVIEW

File: src/main/java/jdwp/Translator.java [hunk 1]
```diff
@@ -192,15 +215,54 @@ public static String normalizeFunc(String func) {
...
+				break;
+			case JAVA_DOUBLE:
+				jniParam = typeSignature.get(JAVA_DOUBLE);
+				break;
+			case JAVA_VOID:
+				jniParam = typeSignature.get(JAVA_VOID);
+				break;
 		}
-		return start + "(" + newParamList + ")";
+		return jniParam;
```
Comment (aavarghese) [inline src/main/java/jdwp/Translator.java:265]: @jchen10500 We could reduce this method to just be `return typeSignature.get(param);` without a switch/case clauses list...wdyt?

Comment (jchen10500) [reply src/main/java/jdwp/Translator.java:265]: :thumbsup:

File: src/test/java/jdwp/TestTranslator.java [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+    /**
+     * Tests for multiple primitive parameters
+     */
+
+
+    /**
+     * Tests the parameters for all the signatures
+     */
+    @Test
+    public void testNormalizePrimitives() {
```
Comment (aavarghese) [inline src/test/java/jdwp/TestTranslator.java:45]: Great!! Thanks @jchen10500 for adding tests as you fixed a bug. 👍

File: src/main/java/jdwp/Translator.java [hunk 3]
```diff
@@ -192,15 +215,21 @@ public static String normalizeFunc(String func) {
...
-		for (int i = 0; i < newParams.size(); i++) {
-			if (i == 0) {
-				newParamList += newParams.get(i);
-			} else {
-				newParamList += ", " + newParams.get(i);
-			}
+
+		StringBuilder newParamList = new StringBuilder();
+		for (String newParam : newParams) {
+			newParamList.append(newParam);
```
Comment (aavarghese) [inline src/main/java/jdwp/Translator.java:221]: Will this add the `", "` in between the params?

Comment (jchen10500) [reply src/main/java/jdwp/Translator.java:221]: This will not because JNI parameters are not separated by commas. 

For example, if the method is: 

``` public static void downLoadProfileImage(String url, String fileName,  int tag, int from)```

then the signature is `(Ljava/lang/String;Ljava/lang/String;II)V`

[Reference](https://stackoverflow.com/questions/22038466/jni-signature-for-method)
